### ISSUE TITLE
Warning invalid props

### ISSUE THREAD

**Issue by micaelomota** [jimmybengtsson/react-native-tags-input#2]
Hi guys, I'm just doing exactly like in the example and I'm gettings these warnings. 
Everything works well, but the annoying warnings are always there. How to get rid of them?
 
```
Warning: Failed prop type: Invalid props.inputContainerStyle key `color` supplied to `Tags`.
Warning: Failed prop type: Invalid props.labelStyle key `color` supplied to `Tags`.
Warning: Failed prop type: Tags: prop type `updateState` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

**Comment by jimmybengtsson** [comment]
Hm, maybe it's because a newer version of React Native.
Will look into this!

**Comment by mgiorgi-github** [comment]
Same issue... can you fix it?
Thanks

**Comment by Agilulfo1820** [comment]
I fixed it this way:
https://github.com/Agilulfo1820/react-native-tags-input/commit/037138069b645deab7d2762648f89936b617558c

**Comment by jimmybengtsson** [comment]
Thanks! @Agilulfo1820 
Will update the repo during this weekend.

**Comment by jimmybengtsson** [comment]
Updated git & npm repo with the changes provided by @Agilulfo1820. Closing this issue!
